#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: osb-atp-existing-instance
spec:
  clusterServiceClassExternalName: atp-service
  clusterServicePlanExternalName: standard
  parameters:
    name: osb-atp-existing-instance
    ocid: "CHANGE_EXISTING_SERVICEINSTANCE_OCID_HERE"
    compartmentId: "CHANGE_COMPARTMENT_OCID_HERE"
    provisioning: false
