#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: oci-service-broker
spec:
  url: http://oci-service-broker.<NAMESPACE_OF_OCI_SERVICE_BROKER>:8080
