#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: "CHANGE_EXISTING_BUCKETNAME_HERE"
spec:
 clusterServiceClassExternalName: object-store-service
 clusterServicePlanExternalName: standard
 parameters:
   name: "CHANGE_EXISTING_BUCKETNAME_HERE"
   namespace: "CHANGE_NAMESPACE_HERE"
   provisioning: false
