#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: Secret
metadata:
  name: adw-secret
data:
  # {"password":"s123456789S@"}
  password: eyJwYXNzd29yZCI6InMxMjM0NTY3ODlTQCJ9
  # {"walletPassword":"Welcome_123"}
  walletPassword: eyJ3YWxsZXRQYXNzd29yZCI6IldlbGNvbWVfMTIzIn0K
